/**
 * Created by lieberli on 2017/5/23.
 */
var lang_chs = {
    "title":"辅助设置",
    "tool_switch":"工具开关",
    "friend":"好友设置",
    "cloud_save":"云存档设置",
    "friend_list":"呼出/收起好友列表",
    "hotkey_conflict_tips":"该键位已被占用!",
    "reply":"快捷回复/发送消息",
    "accept_invite":"邀请类信息-接受",
    "ignore_invite":"邀请类信息-忽略",
    "title_friend":"好友功能",
    "friend_icon":"隐藏在线好友数小图标",
    "friend_msg":"好友消息不提示",
    "friend_state":"好友状态不提示",
    "game_invite":"应用邀请不提示",
    "friend_invite":"请求加好友不提示",
    "title_profile":"云存档设置",
    "auto_sync":"自动同步云存档",
    "auto_sync_desc":"应用启动和退出时，自动同步和上传存档文件",
    "manually_sync":"手动同步云存档",
    "btn_download":"同步到本地",
    "btn_upload":"上传到服务器",
    "btn_set_default":"恢复初始设置",
    "btn_save":"保存",
    "btn_cancel":"取消",
    "game_setting":"应用设置",
    "auto_update":"自动更新",
    "game_directory":"安装目录",
    "uninstall_game":"卸载",
    "show_cross":"展示应用内工具辅助挂件",
    "show_cross_desc":"应用内工具包含社交、截图、精彩时刻等辅助功能",
    "snapshot_cross":"截图时隐藏应用内工具",
    "snapshot_cross_desc":"",
    "test_branch": "版本信息",
    "select_branch": "当前应用版本",
    "uninstall_tips": "应用未安装，请选择分支进行安装",
    "switch_branch": "由于版本差异，切换版本后需要更新；若在更新时取消并切换回原版本，可能导致需要再次更新以复原部分应用文件。",
    "password_enter":"请输入分支密码",
    "password_incorrect":"输入密码有误，请重新输入",
    "password_verified" : "密码验证成功",
    "password_tips": "分支密码",
    "title_tips":"提示",
    "no_test" : "Default - 正式版本",
	"test_ver" : "测试版本",
    //新增的 自定义命令行
    "command" : "启动命令行",
    "title_command" : "启动命令行",
    "command_desc" : "如非必要，请保持此项为空",
    "version_prefix": "版本号：",
    "debug_function": "调试",
    "cheat_test_mode": "打开作弊器测试模式",
    "nickname": "应用昵称",
    "nickname_title": "该昵称将同步在应用内显示",
    "nickname_tips": "30天内只能修改一次",
    "nickname_available": "恭喜你，可以使用这个昵称",
    "nickname_error_format": "仅支持中英文、数字、下划线",
    "nickname_empty_tips": "昵称不能为空",
    "nickname_service_maintain": "系统维护中，昵称修改服务暂时不可用",
    "nickname_not_unique": "该昵称已被占用",
    "nickname_illegal": "昵称内容非法",
    "auto_generate_nickname_tips": "由于检测到您的昵称已被占用，系统为你分配了一个新的昵称，您可在系统维护结束后再次修改！",
    "check_nickname_failed": "查询昵称可用失败，请稍后重试",
    "profile_select_profile_sync_text": "选择需要同步至本地的云存档",
    "profile_upload_time": "上传时间",
    "profile_game_duration": "游戏时长",
    "profile_uploaded_source": "来源",
    "profile_screenshot": "截图",
    "profile_size": "存档大小",
    "profile_warning_text": "*同步云端存档至本地会覆盖本地原有存档，请谨慎操作。",
    "profile_source_all": "全部来源",
    "profile_source_pc": "PC",
    "profile_source_mobile": "移动端",
    "profile_btn_sync_to_local": "同步至本地",
    "profile_unit_day": "天",
    "profile_unit_hour": "时",
    "profile_unit_minute": "分",
    "profile_unit_second": "秒",
    "profile_delete": "删除",
    "profile_no_preview": "当前存档无预览图",
};

var lang_en = {
    "title":"Accessibility",
    "tool_switch":"Tool",
    "friend":"Social",
    "cloud_save":"Cloud Save",
    "friend_list":"Show/Hide friend list",
    "hotkey_conflict_tips":"Hotkey have been used!",
    "reply":"Quick reply/Send message",
    "accept_invite":"Accept invitation",
    "ignore_invite":"Ignore invitation",
    "title_friend":"Social",
    "friend_icon":"Hide online friend(s)",
    "friend_msg":"Hide friend messages",
    "friend_state":"Hide friend state",
    "game_invite":"Hide App invitation",
    "friend_invite":"Hide friend invitation",
    "title_profile":"Cloud Save",
    "auto_sync":"Auto sync",
    "auto_sync_desc":"",
    "manually_sync":"Manual sync",
    "btn_download":"Sync to local",
    "btn_upload":"Sync to server",
    "btn_set_default":"Reset",
    "btn_save":"Save",
    "btn_cancel":"Cancel",
    "game_setting":"App",
    "auto_update":"Auto update",
    "game_directory":"App directory",
    "uninstall_game":"Uninstallation",
    "show_cross":"Enable Helper Tools",
    "show_cross_desc":"Includes social, screenshots and other features",
    "snapshot_cross":"Hide helper tools when taking screenshots",
    "snapshot_cross_desc":"",
    "test_branch": "App Versions",
    "uninstall_tips": "App uninstalled, select branch to install",
    "select_branch": "Current Version",
    "switch_branch": "Due to version differences, the App needs to be updated after switching versions; if you cancel and switch back to the original version during App update, the App may need to be updated again to restore some App files.",
    "password_enter":"Please enter version password",
    "password_incorrect":"Incorrect password",
    "password_verified" : "Password verified!",
    "password_tips": "Enter password",
    "title_tips":"Tips",
    "no_test" : "Default - Release Version",
	"test_ver" : "Test Version",
    //新增的 自定义命令行
    "command" : "Launch Params",
    "title_command" : "Launch Params",
    "command_desc" : "If not necessary, please don't fill in anything.",
    "version_prefix": "Version:",
    "debug_function": "Debug",
    "cheat_test_mode": "Enable cheat mode",
    "nickname": "Nickname",
    "nickname_title": "The nickname will be displayed in the App.",
    "nickname_tips": "Can be modified only once in 30 days.",
    "nickname_available": "This nickname is available.",
    "nickname_error_format": "Ch,En,num and underscores only.",
    "nickname_empty_tips": "Nickname cannot be empty.",
    "nickname_service_maintain": "Unable to change nickname during maintenance.",
    "nickname_not_unique": "The nickname is taken.",
    "nickname_illegal": "Invalid nickname.",
    "auto_generate_nickname_tips": "As your nickname is occupied, a new nickname has been assigned to you, and you can change it after the system maintenance is finished!",
    "check_nickname_failed": "Failed to check the nickname.",
    "profile_select_profile_sync_text": "Select cloud saves you want to sync to local",
    "profile_upload_time": "Uploaded on",
    "profile_game_duration": "Playtime",
    "profile_uploaded_source": "From",
    "profile_screenshot": "Screenshots",
    "profile_size": "Size",
    "profile_warning_text": "*Syncing cloud saves to local will overwrite local saves.",
    "profile_source_all": "All",
    "profile_source_pc": "PC",
    "profile_source_mobile": "Mobile",
    "profile_btn_sync_to_local": "Sync to local",
    "profile_unit_day": "d",
    "profile_unit_hour": "h",
    "profile_unit_minute": "m",
    "profile_unit_second": "s",
    "profile_delete": "delete",
    "profile_no_preview": "No preview for current cloud save",
};

var lang_cht =  {
    "title":"輔助設置",
    "tool_switch":"工具開關",
    "friend":"好友設置",
    "cloud_save":"雲存檔設置",
    "friend_list":"呼出/收起好友列表",
    "hotkey_conflict_tips":"該鍵位已被占用!",
    "reply":"快捷回復/發送消息",
    "accept_invite":"邀請類信息-接受",
    "ignore_invite":"邀請類信息-忽略",
    "title_friend":"好友功能",
    "friend_icon":"隱藏在線好友數小圖標",
    "friend_msg":"好友消息不提示",
    "friend_state":"好友狀態不提示",
    "game_invite":"應用邀請不提示",
    "friend_invite":"請求加好友不提示",
    "title_profile":"雲存檔設置",
    "auto_sync":"自動同步雲存檔",
    "auto_sync_desc":"應用啟動和退出時，自動同步和上傳應用存檔文件",
    "manually_sync":"手動同步雲存檔",
    "btn_download":"同步到本地",
    "btn_upload":"上傳到服務器",
    "btn_set_default":"恢復初始設置",
    "btn_save":"保存",
    "btn_cancel":"取消",
    "game_setting":"應用設置",
    "auto_update":"自動更新",
    "game_directory":"應用目錄",
    "uninstall_game":"卸載應用",
    "show_cross":"展示應用工具輔助掛件",
    "show_cross_desc":"應用工具包含應用內社交、截圖、精彩時刻等輔助功能",
    "snapshot_cross":"截圖時隱藏應用內工具",
    "snapshot_cross_desc":"",
    "test_branch": "版本信息",
    "uninstall_tips": "應用未安裝，請選擇分支進行安裝",
    "select_branch": "當前應用版本",
    "switch_branch": "由於版本差異，切換版本後應用需要更新；若在應用更新時取消並切換回原版本，可能導致應用需要再次更新以復原部分應用文件",
    "password_enter":"請輸入分支密碼",
    "password_incorrect":"輸入密碼有誤，請重新輸入",
    "password_verified" : "密碼驗證成功",
    "password_tips": "分支密碼",
    "title_tips":"提示",
    "no_test" : "Default - 正式版本",
	"test_ver" : "測試版本",
    //新增的 自定義命令行
    "command" : "啟動命令行",
    "title_command" : "啟動命令行",
    "command_desc" : "如非必要，請保持此項為空",
    "version_prefix": "版本號：",
    "debug_function": "調試",
    "cheat_test_mode": "啟用作弊測試",
    "nickname": "套用暱稱",
    "nickname_title": "該暱稱將在應用程式內同步顯示",
    "nickname_tips": "每30天內只能修改一次",
    "nickname_available": "恭喜，該暱稱可以使用",
    "nickname_error_format": "僅支持中英文、數字、下劃線",
    "nickname_empty_tips": "暱稱不能為空",
    "nickname_service_maintain": "系統維護中，暱稱更改服務暫時不可用",
    "nickname_not_unique": "該暱稱已被佔用",
    "nickname_illegal": "暱稱內容非法",
    "auto_generate_nickname_tips": "由於檢測到您的暱稱已被佔用，系統為你分配了一個新的暱稱，您可在系統維護結束後再次修改！",
    "check_nickname_failed": "查詢暱稱可用失敗，請稍後重試",
    "profile_select_profile_sync_text": "選擇需要同步至本地的雲存檔",
    "profile_upload_time": "上傳時間",
    "profile_game_duration": "遊戲時長",
    "profile_uploaded_source": "來源",
    "profile_screenshot": "截圖",
    "profile_size": "存檔大小",
    "profile_warning_text": "*同步雲端存檔至本地會覆蓋本地原有存檔，請謹慎操作。",
    "profile_source_all": "全部來源",
    "profile_source_pc": "PC",
    "profile_source_mobile": "移動端",
    "profile_btn_sync_to_local": "同步至本地",
    "profile_unit_day": "天",
    "profile_unit_hour": "時",
    "profile_unit_minute": "分",
    "profile_unit_second": "秒",
    "profile_delete": "刪除",
    "profile_no_preview": "當前存檔無預覽圖",
};
